-- FAQ inicial del asistente (T7, adelantada en la T6). La FAQ entera va en el prompt (spec, módulo asistente).
-- Reglas del contenido: sin precios ni plazos que Daniel no haya fijado; los clientes no modifican sus
-- webs (los cambios los hace Daniel); "Daniel tiene que revisarlo" indica al asistente que debe escalar.
-- Daniel la edita desde el panel (T11).
insert into public.faq (pregunta, respuesta, categoria, activa) values
  ('Mi web no carga, sale en blanco o da error',
   'Ábrela desde otro dispositivo o con los datos del móvil en lugar del wifi. Si en ningún sitio carga, la web está caída: Daniel tiene que revisarla y se trata como urgente. Si solo falla en un dispositivo, prueba en una ventana de incógnito o borrando la caché del navegador.',
   'web_caida', true),
  ('El navegador avisa de que mi web no es segura o de un problema con el certificado',
   'Suele pasar cuando el certificado de seguridad (el candado de la barra de direcciones) no se ha renovado. Tú no tienes que tocar nada: Daniel tiene que revisarlo. Mientras tanto, no pidas a tus clientes que ignoren el aviso.',
   'dominio_hosting', true),
  ('La web va muy lenta',
   'Abre primero otra web conocida para descartar que sea tu conexión. Si las demás van bien y la tuya tarda mucho en cargar, Daniel tiene que revisarlo: indícale qué páginas van lentas y desde cuándo.',
   'error_funcional', true),
  ('El formulario de contacto no envía o no me llegan los mensajes',
   'Mira primero en la carpeta de spam o correo no deseado: los avisos del formulario a veces acaban ahí. Si el formulario se queda cargando, da un error al enviar o tampoco hay nada en spam, Daniel tiene que revisarlo: indícale en qué web pasa y desde cuándo.',
   'error_funcional', true),
  ('Un enlace o una página da error 404 (página no encontrada)',
   'Indica qué enlace falla y desde dónde lo has abierto (el menú, un botón, Google…). Con eso Daniel puede encontrarlo y corregirlo.',
   'error_funcional', true),
  ('La web se ve mal en el móvil',
   'Recarga la página y prueba a girar el móvil. Si sigue habiendo algo descolocado, como textos cortados o botones que no se pueden pulsar, Daniel tiene que revisarlo: indícale qué página es y con qué móvil lo ves.',
   'error_funcional', true),
  ('El botón de WhatsApp o el de llamar no funciona',
   'Comprueba que el móvil desde el que lo pruebas tiene WhatsApp instalado. Si aun así no abre la conversación, o llama o escribe a un número equivocado, Daniel tiene que revisarlo: indícale en qué web y qué botón falla.',
   'error_funcional', true),
  ('¿Puedo cambiar yo mismo los textos, las fotos o los precios de mi web?',
   'No hace falta que toques nada: los cambios los hace Daniel. Pídelo aquí indicando qué quieres cambiar, en qué página y cómo debe quedar.',
   'cambio_contenido', true),
  ('Quiero cambiar el horario, la dirección o el teléfono',
   'Pídelo aquí con los datos nuevos tal y como deben quedar y en qué web. Daniel hace el cambio y te avisa en esta misma conversación.',
   'cambio_contenido', true),
  ('Quiero actualizar los precios, la carta o los servicios',
   'Pídelo aquí con la lista nueva o con los cambios concretos: qué cambia y cómo debe quedar. Si son varios cambios, ponlos todos en el mismo mensaje para que Daniel los haga de una vez.',
   'cambio_contenido', true),
  ('Quiero cambiar o añadir fotos',
   'Pídelo aquí indicando qué fotos quieres cambiar y en qué página. Daniel te dirá cómo hacerle llegar las fotos nuevas.',
   'cambio_contenido', true),
  ('Quiero añadir algo nuevo a la web: una galería, reservas, una tienda, un blog…',
   'Cuéntanos qué te gustaría añadir y para qué lo necesitas. Daniel lo estudia y te responde con una propuesta.',
   'cambio_contenido', true),
  ('No me llegan los correos de mi dominio',
   'Revisa la carpeta de spam y que el buzón no esté lleno. Si sigues sin recibir correos, Daniel tiene que revisarlo: indícale qué dirección falla y desde cuándo.',
   'correo', true),
  ('Los correos que envío llegan a spam a mis clientes',
   'Puede deberse a la configuración del dominio. Daniel tiene que revisarlo: indícale un ejemplo (a quién escribiste y cuándo) para que pueda comprobarlo.',
   'correo', true),
  ('Me ha llegado un aviso para renovar el dominio o el hosting',
   'No pagues ni pulses enlaces de correos que no esperabas: muchos avisos de renovación son fraudes. Cuéntalo aquí y Daniel te confirma si el aviso es real.',
   'dominio_hosting', true),
  ('Tengo una duda sobre una factura',
   'Indica la fecha o el número de la factura y tu duda. Daniel te responde personalmente en esta conversación.',
   'facturacion', true),
  ('Creo que han hackeado mi web o aparece contenido extraño',
   'No borres nada y no compartas contraseñas por aquí. Indica qué has visto y en qué página: Daniel lo trata como urgente.',
   'otro', true),
  ('Alguien me pide por correo o por teléfono la contraseña de mi web o del hosting',
   'Daniel nunca te pedirá contraseñas por correo, por teléfono ni por este chat. No las compartas y avísale aquí de quién te las ha pedido.',
   'otro', true),
  ('Mi web no aparece en Google',
   'Las webs nuevas pueden tardar unas semanas en aparecer. Prueba a buscar el nombre exacto de tu negocio entre comillas. Si tu web ya aparecía y ha dejado de salir, Daniel tiene que revisarlo.',
   'otro', true),
  ('Quiero hablar directamente con Daniel',
   'Dímelo y abro una incidencia que le llega a Daniel al momento. Te responderá en esta misma conversación.',
   'otro', true);
